version: '3.7'

services:
  node-mongo:
    image: mongo
    container_name: "node-mongo"
    restart: always
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:27017" ]
      interval: 10s
      timeout: 10s

networks:
  api:
    external: true
